----Over all Total revenue
SELECT SUM(TOTAL_price) as revenue
FROM cd_dep.sales;

817860.0508356700
----over all total order
SELECT SUM(TOTAL_ORDER) as total_pizza_order
FROM cd_dep.sales;


21341.9999964980
---Over all total pizza sold
SELECT SUM(quantity) as total_pizza_sold
FROM cd_dep.sales;

49574
---tOver all total pizza sold per order
SELECT SUM(quantity)/sum(TOTAL_ORDER) as pizza_sold_per_order
 FROM cd_dep.sales;

 2.3228
 ----Over all total revenue perorder
 SELECT SUM(TOTAL_price)/ sum(TOTAL_ORDER) as revenue_perorder
FROM cd_dep.sales;

38.32162173038480
----Over all total revenue perpizza
SELECT SUM(TOTAL_price)/ sum(quantity) revenue_perpizza
 FROM cd_dep.sales;

 16.49776194851475

 ----hourly trend
SELECT date_format(order_time,'%h %p') as hours, sum(quantity),sum(TOTAL_ORDER)
FROM cd_dep.sales
group by date_format(order_time,'%h %p')
order by sum(quantity) asc;

# hours, sum(quantity), sum(TOTAL_ORDER)
'09 AM', '4',           '1.0000000000'
'10 AM', '18',          '7.9999999970'
'11 PM', '68',          '27.0399999910'
'10 PM', '1386',        '662.0399998940'
'09 PM', '2545',        '1196.2799998080'
'11 AM', '2728',        '1230.9999998570'
'03 PM', '3216',        '1467.9999997520'
'08 PM', '3534',        '1637.6399997000'
'02 PM', '3613',        '1471.9999997630'
'04 PM', '4239',        '1919.9999996650'
'07 PM', '4406',        '2008.9999996410'
'05 PM', '5211',        '2335.9999995590'
'06 PM', '5417',        '2398.9999995430'
'01 PM', '6413',        '2454.9999996730'
'12 PM', '6776',        '2519.9999996550'



----monthly trend

SELECT column1 as month_order, sum(quantity),sum(TOTAL_ORDER)
FROM cd_dep.sales
group by column1
order by sum(quantity) asc;

# month_order, sum(quantity), sum(TOTAL_ORDER)
October         3883,           1645.9999997410
September,      3890,           1660.9999997270
December,       3935,           1671.9999997650
February,       3961,           1684.9999997030
June,           4107,           1772.9999997320
April,          4151,           1798.9999997000
August,         4168,           1840.9999996980
January,        4232,           1844.9999997000
March,          4261,           1839.9999997050
November,       4266,           1791.9999996680
May,            4328,           1852.9999996870
July,           4392,           1934.9999996720


---Revenue generated by each pizza category 
SELECT pizza_category,sum(total_price) as REVENUE
 FROM cd_dep.sales
 group by  pizza_category
 order by  sum(total_price) DESC;

pizza_category	    REVENUE
Classic	            220053.1000212800
Supreme	            208196.9998138000
Chicken	            195919.5000000000
Veggie	            193690.4510005900


---Revenue generated by each pizza name
SELECT pizza_size,sum(total_price)
 FROM cd_dep.sales
 group by  pizza_size
 order by  sum(total_price) DESC;

 # pizza_size	revenue
Large	375297.9510005900
Medium	249403.0000000000
Regular	178076.4998138000
X-Large	14076.0000000000
XX-Large	1006.6000212800


----top 5 pizza by revenue
SELECT SUBSTRING_INDEX(pizza_name,'_',2) as pizzaname, sum(TOTAL_price) as revenue
 FROM cd_dep.sales
 group by  SUBSTRING_INDEX(pizza_name,'_', 2)
 order by sum(TOTAL_price) DESC
 limit 5;


thai_ckn	43434.2500000000
bbq_ckn	    42768.0000000000
cali_ckn	41409.5000000000
classic_dlx	38180.5000000000
spicy_ital	34831.2500000000
----bottom 5 pizza by revenue
SELECT SUBSTRING_INDEX(pizza_name, '_', 1) as pizzaname, sum(TOTAL_price) as revenue
 FROM cd_dep.sales
 group by  SUBSTRING_INDEX(pizza_name, '_', 1)
 order by sum(TOTAL_price) asc
 limit 5;


brie	         11588.4998138000
green	         13955.7500000000
mediterraneo	 15360.5000000000
spin	         15596.0000000000
calabrese	     15934.2500000000
 ----top 5 pizza by order
 SELECT SUBSTRING_INDEX(pizza_name,'_',1) as pizzaname, sum(TOTAL_order) as totalorder 
 FROM cd_dep.sales
 group by  SUBSTRING_INDEX(pizza_name,'_',1)
 order by sum(TOTAL_order) desc
 limit 5; 


ital	    1841.1379889320
classic	    1072.6043254840
hawaiian	1061.4681844200
bbq	        1045.2844703630
spinach	    1040.3448993650
 ----bottom 5 pizza by order
 SELECT SUBSTRING_INDEX(pizza_name,'_',1)as pizzaname, sum(TOTAL_order) as totalorder
 FROM cd_dep.sales
 group by  SUBSTRING_INDEX(pizza_name,'_',1)
 order by sum(TOTAL_order) asc
 limit 5;


brie	        210.0188921870
calabrese	    401.4518658440
mediterraneo	403.5906925770
spin	        413.6661210340
soppressata	    414.4309201190
 ----bottom 5 pizza by quantity
 SELECT SUBSTRING_INDEX(pizza_name,'_',1)as pizzaname, sum(quantity) as quantity
 FROM cd_dep.sales
 group by  SUBSTRING_INDEX(pizza_name,'_',1)
 order by sum(quantity) desc
 limit 5;


ital	        4303
classic	        2453
bbq	            2432
hawaiian	    2422
pepperoni	    2418
 ----bottom 5 pizza by quantity
 SELECT SUBSTRING_INDEX(pizza_name,'_',1) as pizzaname, sum(quantity) as quantity
 FROM cd_dep.sales
 group by  SUBSTRING_INDEX(pizza_name,'_',1)
 order by sum(TOTAL_order) asc
 limit 5;


brie	        490
calabrese	    937
mediterraneo	934
spin	        970
soppressata	    961